### PR TITLE
Create flashcard project

### PR DESCRIPTION
**Pull request by KKAMLESH286**
Hello Wilfried,

Please check the preview of changes I've made. Please let me know if we need to make any more changes on this part.

Thanks

### CODE REVIEW

**Comment by KKAMLESH286** [comment]
@iwilfried, before merging the Pull request into main branch we can discuss the points here only. You can comment good to go if everything is okay. 

Thanks

**Comment by iwilfried** [comment]
You said before it needs also some text description, only graphics are not enough. Documentation is a bigger challenge than programming. But without there is no success. Code alone is useless.

**Comment by KKAMLESH286** [comment]
Okay, no problem, I'm adding description with these images.

**Comment by iwilfried** [comment]
The start will be bumpy. I tested already half a dozen programmers, everybody gave up or was not talented, but we try again. I also will give input til tomorrow

**Comment by KKAMLESH286** [comment]
Yes, we will try again and as I said before I'll not give up and definitely made this project a success. 

Thanks,

**Pull request merged**
